/**
* This file is auto-generated by nestjs-proto-gen-ts
*/

import { Observable } from 'rxjs';
import { Metadata } from '@grpc/grpc-js';

export namespace blog {
    export interface BlogsService {
        createBlog(
            data: CreateBlogDto,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<blogResponse>;
        findAllBlogs(
            data: EmptyBlog,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Blogs>;
        findOneBlog(
            data: FindOneBlogDto,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Blog>;
        updateBlog(
            data: UpdateBlogDto,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Blog>;
        removeBlog(
            data: FindOneBlogDto,
            metadata?: Metadata,
            ...rest: any[]
        ): Observable<Success>;
    }
    export interface Success {
        message?: string;
    }
    export interface UpdateBlogDto {
        id?: string;
        content?: string;
        author?: string;
    }
    export interface FindOneBlogDto {
        id?: string;
    }
    // tslint:disable-next-line:no-empty-interface
    export interface EmptyBlog {
    }
    export interface Blogs {
        blogs?: blog.Blog[];
    }
    export interface CreateBlogDto {
        content?: string;
        author?: string;
    }
    export interface Blog {
        id?: string;
        content?: string;
        author?: string;
        userId?: string;
    }
    export interface blogResponse {
        message?: string;
        error?: string;
        Blog?: blog.Blog;
    }
}

